[versions]
agp = "9.3.2"

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"


annotation = "1.9.1"
commonsLang3 = "3.18.0"
espressoCoreVersion = "3.7.0"
gson = "2.13.1"
jsoupVersion = "1.21.2"



jsoup = "1.21.2"
myanmarTools = "1.1.3"
playServicesAds = "23.5.0"
exoplayer = "2.19.1"
retrofit = "3.0.0"
runner = "1.7.0"
userMessagingPlatform = "3.2.0"
gridlayout = "1.1.0"
volley = "1.2.1"
exoplayerUi = "2.19.1"
glide = "5.0.0-rc01"
libvlcAll = "4.0.0-eap21"
androidJoda = "2.13.1"
swiperefreshlayoutVersion = "1.1.0"
recyclerviewVersion = "1.4.0"
inappSdkVersion = "5.2.4"
audienceNetworkSdk = "6.20.0"
recyclerviewFastscroll = "2.0.1"
lifecycleExtensions = "2.2.0"
core = "1.17.0"
navigationFragment = "2.9.3"
navigationUi = "2.9.3"
materialVersion = "1.13.0-rc01"
lifecycleProcess = "2.9.3"
circleimageview = "3.1.0"
viewpager2 = "1.1.0"



[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
espresso-core-v360alpha01 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jsoup-v1161 = { module = "org.jsoup:jsoup", version.ref = "jsoupVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
myanmar-tools = { module = "com.google.myanmartools:myanmar-tools", version = "1.2.0" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version = "24.4.0" }
exoplayer = { group = "com.google.android.exoplayer", name = "exoplayer", version.ref = "exoplayer" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
user-messaging-platform = { group = "com.google.android.ump", name = "user-messaging-platform", version.ref = "userMessagingPlatform" }
gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "gridlayout" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
exoplayer-ui = { group = "com.google.android.exoplayer", name = "exoplayer-ui", version.ref = "exoplayerUi" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
libvlc-all = { group = "org.videolan.android", name = "libvlc-all", version.ref = "libvlcAll" }
android-joda = { group = "net.danlew", name = "android.joda", version.ref = "androidJoda" }
#recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayoutVersion" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerviewVersion" }
startapp-inapp-sdk = { group = "com.startapp", name = "inapp-sdk", version.ref = "inappSdkVersion" }
audience-network-sdk = { group = "com.facebook.android", name = "audience-network-sdk", version.ref = "audienceNetworkSdk" }
recyclerview-fastscroll = { group = "com.simplecityapps", name = "recyclerview-fastscroll", version.ref = "recyclerviewFastscroll" }
androidx-lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
circleimageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleimageview" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

